<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-TCPDFOB" failures="1" tests="1" name="Test3" time="69.66" errors="0" timestamp="2022-04-17T11:28:22 IST">
  <testcase classname="TestCases.TC_validatetitle" name="titletest" time="46.807">
    <failure type="java.lang.AssertionError" message="expected [Add New Customer 123] but found [Add New Customer]">
      <![CDATA[java.lang.AssertionError: expected [Add New Customer 123] but found [Add New Customer]
at TestCases.TC_validatetitle.titletest(TC_validatetitle.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- titletest -->
</testsuite> <!-- Test3 -->
